name: McIntosh
favicon: null
layout_spectrum: 0.9749632014427334
typography_spectrum: 0.5574678601697087
title: Mike McIntosh Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.03991539101116359
  saturation: 0
  rhythmicContrast: 0.1480390401557088
purpose: []
